// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmk9ofpMi6DpH16T1INzTkBxJUj9cqr8',
    appId: '1:805821386957:web:4cef19cd7b279ae41a5984',
    messagingSenderId: '805821386957',
    projectId: 'fir-retirement-app',
    authDomain: 'fir-retirement-app.firebaseapp.com',
    storageBucket: 'fir-retirement-app.appspot.com',
    measurementId: 'G-7475XSWX76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhvyf83LtotqQV5kUjzrdm-zvNtSOEM8',
    appId: '1:805821386957:android:45408509dba4eb801a5984',
    messagingSenderId: '805821386957',
    projectId: 'fir-retirement-app',
    storageBucket: 'fir-retirement-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLjQAENj1auAmAoO2EuwGq3wEWbrK0uc',
    appId: '1:805821386957:ios:76d226e2e991c9241a5984',
    messagingSenderId: '805821386957',
    projectId: 'fir-retirement-app',
    storageBucket: 'fir-retirement-app.appspot.com',
    iosClientId: '805821386957-pfqqef009irjgfuqqr1ku2v7brcr4q9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLjQAENj1auAmAoO2EuwGq3wEWbrK0uc',
    appId: '1:805821386957:ios:76d226e2e991c9241a5984',
    messagingSenderId: '805821386957',
    projectId: 'fir-retirement-app',
    storageBucket: 'fir-retirement-app.appspot.com',
    iosClientId: '805821386957-pfqqef009irjgfuqqr1ku2v7brcr4q9e.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
